repos:
    - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
      sha: v1.1.3
      hooks:
      - id: python-safety-dependencies-check

    - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
      sha: v1.0.4
      hooks:
      - id: python-bandit-vulnerability-check
