"""Initial schema

Revision ID: be83538d62e6
Revises:
Create Date: 2020-08-31 22:12:13.754740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "be83538d62e6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tag",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("agile", sa.String(length=64), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("closed", sa.DateTime(), nullable=True),
        sa.Column("due", sa.DateTime(), nullable=True),
        sa.Column("estimate", sa.Float(), nullable=True),
        sa.Column("fun", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.String(length=64), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column("wait", sa.DateTime(), nullable=True),
        sa.Column("willpower", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["task.id"],),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recurrent_task",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("recurrence_type", sa.String(length=64), nullable=True),
        sa.Column("recurrence", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["task.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recurrent_task")
    op.drop_table("task")
    op.drop_table("tag")
    op.drop_table("project")
    # ### end Alembic commands ###
