fulid:
  # Characters used for the generation of identifiers.
  characters: asdfghjwer

  # Characters forbidden to be used in the generation of ids, due to
  # ulid converting them to numbers or because they have a meaning
  # for the terminal.
  forbidden_characters: ilou|&:;()<>~*@?!$#[]{}\/'"`

# Configuration of the reports.
report:
  # Datetime strftime compatible string to print dates.
  date_format: '%Y-%m-%d %H:%M'

  # Configuration of the frozen report.
  frozen:
    # Ordered list of Task attributes to print.
    columns: [id, description, recurrence, recurrence_type, project_id, priority, tags, due, parent_id]
    # Ordered list of names for the Task attributes to print.
    labels: [ID, Description, Recurrence, Recurrence Type, Project, Pri, Tags, Due, Parent]

  # Configuration of the open report.
  open:
    # Ordered list of Task attributes to print.
    columns: [id, description, project_id, priority, tags, due]
    # Ordered list of names for the Task attributes to print.
    labels: [ID, Description, Project, Pri, Tags, Due]

  # Configuration of the projects report.
  projects:
    # Ordered list of Task attributes to print.
    columns: [id, task.count, description]
    # Ordered list of names for the Task attributes to print.
    labels: [Name, Tasks, Description]

  # Configuration of the repeating report.
  repeating:
    # Ordered list of Task attributes to print.
    columns: [id, description, recurrence, project_id, priority, tags, due]
    # Ordered list of names for the Task attributes to print.
    labels: [ID, Description, Recurrence, Project, Pri, Tags, Due]

  # Configuration of the recurring report.
  recurring:
    # Ordered list of Task attributes to print.
    columns: [id, description, recurrence, project_id, priority, tags, due]
    # Ordered list of names for the Task attributes to print.
    labels: [ID, Description, Recurrence, Project, Pri, Tags, Due]

  # Configuration of the projects report.
  tags:
    # Ordered list of Task attributes to print.
    columns: [id, task.count, description]
    # Ordered list of names for the Task attributes to print.
    labels: [Name, Tasks, Description]

task:
  agile_default_state:
    # Agile allowed states.

# Level of logging verbosity. One of ['info', 'debug', 'warning'].
verbose: info

# Storage configuration
storage:
  # Type of storage. One of ['sqlite']
  type: sqlite

  # Configuration of the sqlite storage backend
  sqlite:
    path: ~/.local/share/pydo/sqlite.db
