name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Black
        uses: psf/black@stable
      - name: Flake8
        uses: cclauss/GitHub-Action-for-Flake8@v0.5.0
